version: "3.8"

services:
  portfolix:
    container_name: portfolix
    image: "docker.pkg.github.com/mervin16/portfolix/portfolix:${PORTFOLIX_VERSION}"
    networks:
      - portfolix_net
    expose:
      - 8084
    env_file:
      - secret.env
    environment:
      - PORTFOLIX_VERSION=${PORTFOLIX_VERSION}
    restart: always

  nginx_portfolix:
    image: nginx
    container_name: nginx_portfolix
    ports:
      - "8084:80"
    networks:
      - portfolix_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - portfolix
    restart: always

networks:
  portfolix_net:
    name: portfolix_network
    driver: bridge
