version: "3.8"

services:
  portfolix:
    container_name: portfolix
    image: "docker.pkg.github.com/mervin16/portfolix/portfolix:${PORTFOLIX_VERSION}"
    networks:
      - portfolix_net
    ports:
      - 8084:8084
    restart: always
    env_file:
      - secret.env
    environment:
      - PORTFOLIX_VERSION=${PORTFOLIX_VERSION}

networks:
  portfolix_net:
    name: portfolix_network
    driver: bridge