version: "3.8"

services:
  th3pl4gu3:
    container_name: th3pl4gu3
    image: "docker.pkg.github.com/mervin16/th3pl4gu3/th3pl4gu3:${TH3PL4GU3_VERSION}"
    networks:
      - th3pl4gu3_net
    expose:
      - 8082
    restart: always
    env_file:
      - secret.env
    environment:
      - TH3PL4GU3_VERSION=${TH3PL4GU3_VERSION}

  nginx_th3pl4gu3:
    image: nginx
    container_name: nginx_th3pl4gu3
    ports:
      - "8082:80"
    networks:
      - th3pl4gu3_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - th3pl4gu3
    restart: always

networks:
  th3pl4gu3_net:
    name: th3pl4gu3_network
    driver: bridge